---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: url-shortener
  name: url-shortener-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: url-shortener
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener
  labels:
    app: url-shortener
spec:
  selector:
    matchLabels:
      app: url-shortener
  template:
    metadata:
      labels:
        app: url-shortener
    spec:
      containers:
      - image: ishantanu16/gourlshortener:v1
        imagePullPolicy: Always
        name: gourlshortener
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: bolt-volumeclaim
          mountPath: /boltdb-data
       
      volumes:
      - name: bolt-volumeclaim
        persistentVolumeClaim:
          claimName: bolt-volumeclaim   
